apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  labels:
    app: frontend
    stage: dev
  generateName: frontend-build-
spec:
  serviceAccountName: sa-pipeline-runner
  pipelineRef:
    name: buildah
  params:
  - name: build-stage
    value: dev
  - name: git-repo-name
    value: frontend
  - name: git-branch
    value: master
  - name: git-url
    value: "http://gitea.gitea:3000/argo"
  - name: image-url
    value: "docker.kw01"
  - name: gitops-repo-name
    value: frontend-deploy
  - name: gitops-branch
    value: kust
  workspaces:
  - name: source
    persistentvolumeclaim:
      claimName: pvc-build
    subPath: $(context.pipelineRun.name)
  - name: gitops
    emptyDir: {}
