{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-context-support",
    "version": "6.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.1.10.jar",
          "url": "spring-context-support-6.1.10.jar",
          "size": 173311,
          "sha512": "44a8bede20b85ae48c4567a3f2cd2b4dcabaa146ff1da008f68402c8dcb4e9461c697ca8cd490dc54f047f3749d76f9d88fbf592b468f26aefa678ffc4f7591c",
          "sha256": "435c3e1d4c5b5c609b02e0ad80eef380bed1be074f2827bd6b858dd119680157",
          "sha1": "e51a2bdfcc004ae6e420edcfb29e628aaf26e00c",
          "md5": "227911df8dfdfc09ab497666e56003e5"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-context-support-6.1.10.jar",
          "url": "spring-context-support-6.1.10.jar",
          "size": 173311,
          "sha512": "44a8bede20b85ae48c4567a3f2cd2b4dcabaa146ff1da008f68402c8dcb4e9461c697ca8cd490dc54f047f3749d76f9d88fbf592b468f26aefa678ffc4f7591c",
          "sha256": "435c3e1d4c5b5c609b02e0ad80eef380bed1be074f2827bd6b858dd119680157",
          "sha1": "e51a2bdfcc004ae6e420edcfb29e628aaf26e00c",
          "md5": "227911df8dfdfc09ab497666e56003e5"
        }
      ]
    }
  ]
}
