{
  "formatVersion": "1.1",
  "component": {
    "group": "io.projectreactor",
    "module": "reactor-core",
    "version": "3.6.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.6.7.jar",
          "url": "reactor-core-3.6.7.jar",
          "size": 1875219,
          "sha512": "1acc98fe44e9a17c9cf3aa13dab7e997b1466ebb277b8330fc6b2350f27bafff27e9300e42a99fb91bbc4a77e1a23c6cad83d602a0341a3fdfe5b82ccbb7df9d",
          "sha256": "34d34caad35ab8153ff6e70e2e4634c035fee6af7bcae78f95418a488c0fbcda",
          "sha1": "6d1918147645b5b8e577555a89ab271319f25d2f",
          "md5": "e77615bc7b60f8a5098d10db79eae1e1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.4"
          }
        }
      ],
      "files": [
        {
          "name": "reactor-core-3.6.7.jar",
          "url": "reactor-core-3.6.7.jar",
          "size": 1875219,
          "sha512": "1acc98fe44e9a17c9cf3aa13dab7e997b1466ebb277b8330fc6b2350f27bafff27e9300e42a99fb91bbc4a77e1a23c6cad83d602a0341a3fdfe5b82ccbb7df9d",
          "sha256": "34d34caad35ab8153ff6e70e2e4634c035fee6af7bcae78f95418a488c0fbcda",
          "sha1": "6d1918147645b5b8e577555a89ab271319f25d2f",
          "md5": "e77615bc7b60f8a5098d10db79eae1e1"
        }
      ]
    }
  ]
}
