{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-configuration-processor",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.3.1.jar",
          "url": "spring-boot-configuration-processor-3.3.1.jar",
          "size": 129840,
          "sha512": "ba6cb2ef68c8681330bbd084058ff2a00cf4073b3563fb988f7a19c6046ef8e16f00267a2efe5ccaff022c5e0190254d728d37443f007e0cdaa2a539df494c0a",
          "sha256": "9d8156956b14190adb5244559eae32ceecb3a77c07d9c6e82c55b99e1d96c8b2",
          "sha1": "631629214272c316ec66e453fde42638392144fa",
          "md5": "6a9af70c75a499499133755d077304f9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.3.1.jar",
          "url": "spring-boot-configuration-processor-3.3.1.jar",
          "size": 129840,
          "sha512": "ba6cb2ef68c8681330bbd084058ff2a00cf4073b3563fb988f7a19c6046ef8e16f00267a2efe5ccaff022c5e0190254d728d37443f007e0cdaa2a539df494c0a",
          "sha256": "9d8156956b14190adb5244559eae32ceecb3a77c07d9c6e82c55b99e1d96c8b2",
          "sha1": "631629214272c316ec66e453fde42638392144fa",
          "md5": "6a9af70c75a499499133755d077304f9"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.3.1-javadoc.jar",
          "url": "spring-boot-configuration-processor-3.3.1-javadoc.jar",
          "size": 185381,
          "sha512": "0d64449508a120ef6eb09cca3c57f33112bd16c156bb42a9a871865aba30753f37b57af898d6dab8d3fb6fad3fa4fa9b4fb8a524f370c57388850844700ba290",
          "sha256": "4ce6ef06e929e976736ddadbe71d09150efaf4a9b1297667f04b5655fb570bfd",
          "sha1": "126ebefd1e1ca806d96118b33e724b5cccd821eb",
          "md5": "34323d07900a02266f1dc7bd85df9115"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.3.1-sources.jar",
          "url": "spring-boot-configuration-processor-3.3.1-sources.jar",
          "size": 84177,
          "sha512": "58a0edcc849f7c3ba05036ed1aea0988123a3de4493297a8afc3e325bdd543bc05a5c2c1300889574acb0c3cc6b64b99324d676c2ce0d9dcc4568b9a64731cb8",
          "sha256": "a7fe96b0504ac48aa347af8b5759cf13804d145eecd093d0cc067524a3c7cb4d",
          "sha1": "5459b1bc5ae0e8ea778426bc6709c81d1b918235",
          "md5": "6751188f8e7d2136130cf1495d4a0669"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.3.1.jar",
          "url": "spring-boot-configuration-processor-3.3.1.jar",
          "size": 129840,
          "sha512": "ba6cb2ef68c8681330bbd084058ff2a00cf4073b3563fb988f7a19c6046ef8e16f00267a2efe5ccaff022c5e0190254d728d37443f007e0cdaa2a539df494c0a",
          "sha256": "9d8156956b14190adb5244559eae32ceecb3a77c07d9c6e82c55b99e1d96c8b2",
          "sha1": "631629214272c316ec66e453fde42638392144fa",
          "md5": "6a9af70c75a499499133755d077304f9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-configuration-processor-maven-optional",
          "version": "3.3.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-configuration-processor-3.3.1.jar",
          "url": "spring-boot-configuration-processor-3.3.1.jar",
          "size": 129840,
          "sha512": "ba6cb2ef68c8681330bbd084058ff2a00cf4073b3563fb988f7a19c6046ef8e16f00267a2efe5ccaff022c5e0190254d728d37443f007e0cdaa2a539df494c0a",
          "sha256": "9d8156956b14190adb5244559eae32ceecb3a77c07d9c6e82c55b99e1d96c8b2",
          "sha1": "631629214272c316ec66e453fde42638392144fa",
          "md5": "6a9af70c75a499499133755d077304f9"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-configuration-processor-maven-optional",
          "version": "3.3.1"
        }
      ]
    }
  ]
}
