{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-webmvc",
    "version": "6.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.10.jar",
          "url": "spring-webmvc-6.1.10.jar",
          "size": 1046856,
          "sha512": "c538b46f1d8872f766e9c26bf54f7e4d240e981b9968c1f734425e3598d37971a369c8f27205e861b5076427324beedb7becee51916b61432847d8c4c805c197",
          "sha256": "74bd3e7abf4bc2bc1b5881292deba9303011196fda49b647b1917bd0a418ac24",
          "sha1": "476344c2f21ab070bc72108375d9355f2ec0ddd1",
          "md5": "26334093180c432be6b31933f3218a78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-context",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-expression",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-web",
          "version": {
            "requires": "6.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-webmvc-6.1.10.jar",
          "url": "spring-webmvc-6.1.10.jar",
          "size": 1046856,
          "sha512": "c538b46f1d8872f766e9c26bf54f7e4d240e981b9968c1f734425e3598d37971a369c8f27205e861b5076427324beedb7becee51916b61432847d8c4c805c197",
          "sha256": "74bd3e7abf4bc2bc1b5881292deba9303011196fda49b647b1917bd0a418ac24",
          "sha1": "476344c2f21ab070bc72108375d9355f2ec0ddd1",
          "md5": "26334093180c432be6b31933f3218a78"
        }
      ]
    }
  ]
}
