kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: airflow
  name: clusterrole-airflow-kubectl
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - create
      - get
      - list
      - delete
      - watch
  - apiGroups: ["apps"]
    resources:
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
    verbs:
      - create
      - get
      - list
      - patch
      - update
      - watch
      - scale
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrole-bidning-airflow-kubectl
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterrole-airflow-kubectl
subjects:
  - kind: ServiceAccount
    name: default
    namespace: airflow
