{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-jooq",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.19.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jooq-3.3.1.jar",
          "url": "spring-boot-starter-jooq-3.3.1.jar",
          "size": 4804,
          "sha512": "c09a2a39d4981f452d84b6e30599c9a98db7be1ebccb2a6af63ab3424d06545576e71901ae88ed7efd4a4f8d527f8260f11e78d8b23c94364c9402ffb0778726",
          "sha256": "99da0d80d48daf41e07353e43f728d761486accdbb7c8c6d420dec82c4d7cd23",
          "sha1": "2c09d5cf591ded0218352339b09a1135d82e3d5f",
          "md5": "1350b8d78a680027e185d8ab58fc483d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-jdbc",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-tx",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.jooq",
          "module": "jooq",
          "version": {
            "requires": "3.19.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-jooq-3.3.1.jar",
          "url": "spring-boot-starter-jooq-3.3.1.jar",
          "size": 4804,
          "sha512": "c09a2a39d4981f452d84b6e30599c9a98db7be1ebccb2a6af63ab3424d06545576e71901ae88ed7efd4a4f8d527f8260f11e78d8b23c94364c9402ffb0778726",
          "sha256": "99da0d80d48daf41e07353e43f728d761486accdbb7c8c6d420dec82c4d7cd23",
          "sha1": "2c09d5cf591ded0218352339b09a1135d82e3d5f",
          "md5": "1350b8d78a680027e185d8ab58fc483d"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-jooq-3.3.1.jar",
          "url": "spring-boot-starter-jooq-3.3.1.jar",
          "size": 4804,
          "sha512": "c09a2a39d4981f452d84b6e30599c9a98db7be1ebccb2a6af63ab3424d06545576e71901ae88ed7efd4a4f8d527f8260f11e78d8b23c94364c9402ffb0778726",
          "sha256": "99da0d80d48daf41e07353e43f728d761486accdbb7c8c6d420dec82c4d7cd23",
          "sha1": "2c09d5cf591ded0218352339b09a1135d82e3d5f",
          "md5": "1350b8d78a680027e185d8ab58fc483d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-jooq-maven-optional",
          "version": "3.3.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jooq-3.3.1.jar",
          "url": "spring-boot-starter-jooq-3.3.1.jar",
          "size": 4804,
          "sha512": "c09a2a39d4981f452d84b6e30599c9a98db7be1ebccb2a6af63ab3424d06545576e71901ae88ed7efd4a4f8d527f8260f11e78d8b23c94364c9402ffb0778726",
          "sha256": "99da0d80d48daf41e07353e43f728d761486accdbb7c8c6d420dec82c4d7cd23",
          "sha1": "2c09d5cf591ded0218352339b09a1135d82e3d5f",
          "md5": "1350b8d78a680027e185d8ab58fc483d"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-jooq-maven-optional",
          "version": "3.3.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jooq-3.3.1-javadoc.jar",
          "url": "spring-boot-starter-jooq-3.3.1-javadoc.jar",
          "size": 4742,
          "sha512": "bb40f8d3091959bd9902d7776bea6e1e77b5376fef17bb87a12bea53233d8509d621c5ff7e2d120b348960cc476f014087b886913294f5f4ff5ea403c81dbe03",
          "sha256": "edbcaba1e782762a132e7da7ee357328a46a1d31d08765a2175117856dcb974e",
          "sha1": "c6c3f148aa08faf620da58ad866a688e11509d24",
          "md5": "fe72b028de6350ef1bba50452d08d70c"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-jooq-3.3.1-sources.jar",
          "url": "spring-boot-starter-jooq-3.3.1-sources.jar",
          "size": 4740,
          "sha512": "f438d7daca6082992e4eb42a51749bad71d53d8dea2d88d66fe7c17720450093e8c7c385100a0cce6f0242109a722dfa78fb9155a04969a72f60b85b72d1b57d",
          "sha256": "82919d088db7b782d02e522be0e58f1aa15969d84d98df5781d0e26ec350271a",
          "sha1": "01c4b541de4a3165b5cd6e835204da9ae8938f7d",
          "md5": "bd3c9f3a517baf8b5fb7cd4ec57ae759"
        }
      ]
    }
  ]
}
