{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jooq",
    "module": "jooq-codegen-gradle",
    "version": "3.19.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "jooq-codegen-gradle-3.19.10.jar",
          "url": "jooq-codegen-gradle-3.19.10.jar",
          "size": 86594,
          "sha512": "b80c343b02dfa773142ee0f0c45ca24f2367957ef67e47ec503109a71c7fe56a314e6cdd62c98a0be6b88c5b5c96f02f26d1506cd104689829a9b5a308bfdf13",
          "sha256": "c2ae65308e1da25f566fc203710edfe4032c384f300655fc0af402c1851e881d",
          "sha1": "ee9fc4a56f5d5a233e26443db07eaf02a99e1f1a",
          "md5": "edaeba0db42e34254586d70abbed5737"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jooq",
          "module": "jooq-codegen",
          "version": {
            "requires": "3.19.10"
          }
        }
      ],
      "files": [
        {
          "name": "jooq-codegen-gradle-3.19.10.jar",
          "url": "jooq-codegen-gradle-3.19.10.jar",
          "size": 86594,
          "sha512": "b80c343b02dfa773142ee0f0c45ca24f2367957ef67e47ec503109a71c7fe56a314e6cdd62c98a0be6b88c5b5c96f02f26d1506cd104689829a9b5a308bfdf13",
          "sha256": "c2ae65308e1da25f566fc203710edfe4032c384f300655fc0af402c1851e881d",
          "sha1": "ee9fc4a56f5d5a233e26443db07eaf02a99e1f1a",
          "md5": "edaeba0db42e34254586d70abbed5737"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jooq-codegen-gradle-3.19.10-javadoc.jar",
          "url": "jooq-codegen-gradle-3.19.10-javadoc.jar",
          "size": 363096,
          "sha512": "a1908fd1e6ce23de4ada2946bdc39b89408d43a830463e7e5a38fac9bfd20f58fe2ed1ba6f6e65389e2167038f2530ec4cf2f575ae9608e0d287fa065b4e43e8",
          "sha256": "59e31ff7ed330fe7c53cf25a5cd1d53ab948e9cbca7db0724176e42c91ffccc8",
          "sha1": "35798965cf819b32523bdda61f405962ee27dde2",
          "md5": "8d6b62e0e69f68ac4d9eecd132e589bb"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jooq-codegen-gradle-3.19.10-sources.jar",
          "url": "jooq-codegen-gradle-3.19.10-sources.jar",
          "size": 12685,
          "sha512": "da3075aa4c88d39dcd52bdd90b7d9bfefbc076f154fcb5b381b43bfc926bec5c625ab9b71989f78cc16c410ba5330d62d7b7b0170e4522348e13392094f25fee",
          "sha256": "d0ffdda88ad9eea6dc19fd1b7428bc63cd125fa512bc500f9feec70ac642e410",
          "sha1": "0f6d9344a6fcff20601cad58be5f6d669b8ec5a0",
          "md5": "2e530ab4378a2a3d0ef29ba68253652b"
        }
      ]
    }
  ]
}
