FROM python:3.8
# 
RUN apt update -y && apt install wget curl unzip software-properties-common -y 
#
WORKDIR /src
RUN wget https://download.oracle.com/otn_software/linux/instantclient/217000/instantclient-basic-linux.x64-21.7.0.0.0dbru.zip
RUN wget https://download.oracle.com/otn_software/linux/instantclient/217000/instantclient-sdk-linux.x64-21.7.0.0.0dbru.zip
RUN unzip instantclient-basic-linux.x64-21.7.0.0.0dbru.zip && rm -f instantclient-basic-linux.x64-21.7.0.0.0dbru.zip
RUN unzip instantclient-sdk-linux.x64-21.7.0.0.0dbru.zip && rm -f instantclient-sdk-linux.x64-21.7.0.0.0dbru.zip
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/src/instantclient_21_7"
RUN ldconfig -V
RUN apt update -y && apt install libaio1 libaio-dev
RUN pip install twine
