{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework",
    "module": "spring-oxm",
    "version": "6.1.10",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.1.10.jar",
          "url": "spring-oxm-6.1.10.jar",
          "size": 59963,
          "sha512": "07c17e42e91b530b11c65a2f78762a756deda2ab65caac4c2e253b3795b6ae41ef436047b749132042568d33b99050c034a9ad7ed7e051175889f0cf39553686",
          "sha256": "58520ebdd4b4da4740eac04e5faa4861dd564d4de3f1783954f793c047f89d01",
          "sha1": "9db3d67a285fca31091d7c97a45de68842c38796",
          "md5": "7942778553caa1a675b3c83e3acad5ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework",
          "module": "spring-beans",
          "version": {
            "requires": "6.1.10"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-core",
          "version": {
            "requires": "6.1.10"
          }
        }
      ],
      "files": [
        {
          "name": "spring-oxm-6.1.10.jar",
          "url": "spring-oxm-6.1.10.jar",
          "size": 59963,
          "sha512": "07c17e42e91b530b11c65a2f78762a756deda2ab65caac4c2e253b3795b6ae41ef436047b749132042568d33b99050c034a9ad7ed7e051175889f0cf39553686",
          "sha256": "58520ebdd4b4da4740eac04e5faa4861dd564d4de3f1783954f793c047f89d01",
          "sha1": "9db3d67a285fca31091d7c97a45de68842c38796",
          "md5": "7942778553caa1a675b3c83e3acad5ec"
        }
      ]
    }
  ]
}
