{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-data-redis",
    "version": "3.3.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.4"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.3.2.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.3.1.jar",
          "url": "spring-boot-starter-data-redis-3.3.1.jar",
          "size": 4784,
          "sha512": "a334a6af1a0156e97075a2ac5e76656892e4adf955f312044540a7039bead56978fc9cb3934306d5756453d6dae9cbc8446af187ea9da0c2e0f45f49a5d298bb",
          "sha256": "08aa82289f00048ced5f3bb10f1b87d0c61db2378f00603abbd908618032cdda",
          "sha1": "70fa6c5821196887e0253f594914474ace0f0f36",
          "md5": "ddb930e9c080c71c7366cd8b00138b24"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "3.3.1"
          }
        },
        {
          "group": "io.lettuce",
          "module": "lettuce-core",
          "version": {
            "requires": "6.3.2.RELEASE"
          }
        },
        {
          "group": "org.springframework.data",
          "module": "spring-data-redis",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.3.1.jar",
          "url": "spring-boot-starter-data-redis-3.3.1.jar",
          "size": 4784,
          "sha512": "a334a6af1a0156e97075a2ac5e76656892e4adf955f312044540a7039bead56978fc9cb3934306d5756453d6dae9cbc8446af187ea9da0c2e0f45f49a5d298bb",
          "sha256": "08aa82289f00048ced5f3bb10f1b87d0c61db2378f00603abbd908618032cdda",
          "sha1": "70fa6c5821196887e0253f594914474ace0f0f36",
          "md5": "ddb930e9c080c71c7366cd8b00138b24"
        }
      ]
    },
    {
      "name": "mavenOptionalApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.3.1.jar",
          "url": "spring-boot-starter-data-redis-3.3.1.jar",
          "size": 4784,
          "sha512": "a334a6af1a0156e97075a2ac5e76656892e4adf955f312044540a7039bead56978fc9cb3934306d5756453d6dae9cbc8446af187ea9da0c2e0f45f49a5d298bb",
          "sha256": "08aa82289f00048ced5f3bb10f1b87d0c61db2378f00603abbd908618032cdda",
          "sha1": "70fa6c5821196887e0253f594914474ace0f0f36",
          "md5": "ddb930e9c080c71c7366cd8b00138b24"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-redis-maven-optional",
          "version": "3.3.1"
        }
      ]
    },
    {
      "name": "mavenOptionalRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.3.1.jar",
          "url": "spring-boot-starter-data-redis-3.3.1.jar",
          "size": 4784,
          "sha512": "a334a6af1a0156e97075a2ac5e76656892e4adf955f312044540a7039bead56978fc9cb3934306d5756453d6dae9cbc8446af187ea9da0c2e0f45f49a5d298bb",
          "sha256": "08aa82289f00048ced5f3bb10f1b87d0c61db2378f00603abbd908618032cdda",
          "sha1": "70fa6c5821196887e0253f594914474ace0f0f36",
          "md5": "ddb930e9c080c71c7366cd8b00138b24"
        }
      ],
      "capabilities": [
        {
          "group": "org.springframework.boot",
          "name": "spring-boot-starter-data-redis-maven-optional",
          "version": "3.3.1"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.3.1-javadoc.jar",
          "url": "spring-boot-starter-data-redis-3.3.1-javadoc.jar",
          "size": 4747,
          "sha512": "bd25f35307c082d108e5c31e095155bf149ddfcc1d899f45eeefd8575f98c4f648a9fb21d42ea160428368e85ef8cfa623e161e69fa2b26157e55b76ba3b9ba5",
          "sha256": "928a35b9a3d80179f00f655ff2b19619cd9202d3a3642689b54fa64fcac29bd4",
          "sha1": "3cd55f3158dfb724ad76a1b9b5e54615b61299ab",
          "md5": "c29cc9b22cdaf8679fc3cf95d97d62c7"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-data-redis-3.3.1-sources.jar",
          "url": "spring-boot-starter-data-redis-3.3.1-sources.jar",
          "size": 4746,
          "sha512": "6f0feaadc8939561b9bf104004c4946f95a6761233927d16e7edd6b2421c13ea4cc5b6f9fd546e05bcd796977f25adc636a5d104dd798c53fcfe7ca49ad3b92e",
          "sha256": "49fe59aa14fb5c76c08495e0683d8ce61f27df1de9f675286a62908f188e15ce",
          "sha1": "25decd2170dc886fa54157a1143269497ddebde0",
          "md5": "2038b4ce4c5fe4c65d6a2a1e04b141d7"
        }
      ]
    }
  ]
}
